### ISSUE TITLE
How can we disable animations on small screens?

### ISSUE THREAD

**Issue by nicolay-zlobin** [BinarCode/vue2-transitions#11]

**Comment by cristijora** [comment]
One option would be to pass `:duration="0"` to the components
Another is to do it via css
If you look into the source code, there are animations like this
```
.scaleIn {
    animation-name: scaleIn;
}
```
You can add a media query add set it to unset

```
@media (max-width: 700px){
 .scaleIn {
   animation-name: unset;
 }
}
```

**Comment by nicolay-zlobin** [comment]
Thank you!
