### ISSUE TITLE
Support for appear

### ISSUE THREAD

**Issue by andreasvirkus** [BinarCode/vue2-transitions#14]
First off, we love the library!

Could we also have support for the appear keyword?

https://vuejs.org/v2/guide/transitions.html#Transitions-on-Initial-Render

Best,
Andreas

**Comment by Yakoot** [comment]
great library, but i cannot use it without appear =( any news about it?

**Comment by cristijora** [comment]
@andreasvirkus @Yakoot Actually it does support appear. The library is just a wrapper over `transition` component. Any prop that `transition` component supports, the other components will also support it.

Also `appear` is already used inside the example code and works https://binarcode.github.io/vue2-transitions/
