### ISSUE TITLE
[Demo] Wrong animation group code example

### ISSUE THREAD

**Issue by MyIsaak** [BinarCode/vue2-transitions#26]
Visit the demo: https://binarcode.github.io/vue2-transitions/

When you want to view the example code of _group animation_ versus _simple animation_, it shows the inversed result. So setting the toggle to _group_ the example code shows single animation code and displays:
```
<fade-transition>
    <div v-show="show">Your content here</div> 
  </fade-transition>
```
Rather than the correct group code:
```
<fade-transition group>
    <div v-show="show">Your content here</div> 
  </fade-transition>
```

An easy fix would be to swap the group with simple toggle so that the right example code is displayed.

**Comment by hrastnik** [comment]
I've noticed this too.

Here's an image showing the wrong prop being passed to transition

![image](https://user-images.githubusercontent.com/3407234/63431911-4361ef00-c420-11e9-9aa5-d0ceb1c59b69.png)

**Comment by andreasvirkus** [comment]
This was fixed with https://github.com/BinarCode/vue2-transitions/pull/20
