### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by bovas85** [BinarCode/vue2-transitions#5]
How do you extend to other animations?

I can only use the ones listed.

Thank you

**Comment by cristijora** [comment]
Hi @bovas85 
You can look how each transition is implemented. They are pretty much the same except Collapse one.
https://github.com/cristijora/vue2-transitions/blob/master/src/Zoom/ZoomCenterTransition.vue

template
```html
 <component :is="componentType"
             :tag="tag"
             v-bind="$attrs"
             v-on="hooks"
             enter-active-class="zoomIn"
             move-class="zoom-move"
             leave-active-class="zoomOut">
    <slot></slot>
  </component>
```

script
```js
import {baseTransition} from 'vue2-transitions/mixins/index.js'
  export default {
    name: 'zoom-center-transition',
    mixins: [baseTransition]
  }
```

Add you enter and leave active classes and name the transition how you want.
`move-class` is necessary for group transitions only. 
Then the usage would be the same as the rest of the components.
You can get new animations you need directly from [animate css source code](https://github.com/daneden/animate.css/blob/master/source/zooming_entrances/zoomIn.css) or have your own.

The only gotcha is to not specify the `animation-duration` inside css as that will be added by the mixin through the `:duration` prop.

**Comment by bovas85** [comment]
I'm using nuxt, how do I load the empty component and pass props to it?

**Comment by cristijora** [comment]
What do you mean by empty?
Post some code please so I can understand
